name: Xray-classification

conda_env: conda.yaml

entry_points:
    main:
        parameters:
            config: {type: str , default: 'config/config.yaml'}
        command: "python main.py -c {config}"

    ingest_data:
        parameters:
            config: {type: str , default: 'config/config.yaml'}
        command: "python src/ingestion.py -c {config}"

    train:
        parameters:
            config: {type: str , default: 'config/config.yaml'}
        command: "python src/train.py -c {config}"
    
    validate:
        parameters:
            config: {type: str , default: 'config/config.yaml'}
        command: "python src/validation.py -c {config}"